#! /bin/bash
# set -x

BASE=/projects/message-hub/support/tools
CURRENT=`head $BASE/scripts/current`

# echo "rewind..."
echo -e "\033[33mrewind...\033[0m"
echo "step $(($CURRENT)) discarded."
step "$(($CURRENT-1))"