# On shutdown it reduces waiting time when stoping Camel's streaming listener
camel.main.shutdownTimeout = 5

# Discord credentials
discord.token=syt_dXNlcjM_IzNwDAnUXjGKciDkZBbm_3Aoy3z
discord.room=!CGzHallMgSeYmlDlrH:rhintegration.demo
