apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: s2k
  annotations:
    trait.camel.apache.org/mount.configs: "secret:stage3"
    trait.camel.apache.org/mount.resources: "configmap:stage3-transform"
spec:

  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: slack-source
    properties:
      token: "{{slack.token}}"
      channel:  "{{slack.channel.name}}"
      delay: 2000

  steps:

  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: log-sink

  # Filter Slack's Bot messages (messages from other platforms)
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: predicate-filter-action
    properties:
      expression: $.user!='U03NW6H8N5V'
   
  - ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: jslt-action
    properties:
      template: s2k.jslt


  sink:
    ref:
      kind: KafkaTopic
      apiVersion: kafka.strimzi.io/v1beta1
      name: room1

  # sink:
  #   ref:
  #     kind: Kamelet
  #     apiVersion: camel.apache.org/v1
  #     name: log-sink    