# On shutdown it reduces waiting time when stoping Camel's streaming listener
camel.main.shutdownTimeout = 5

# Matrix credentials
matrix.token=syt_dXNlcjI_xVtebNTKpLPpvPhLClLt_1QqczQ
matrix.room=!gjrFpoMPWptQLwKfDJ:rhintegration.demo

# Rocket.Chat credentials
rocketchat.token=ToMEoFPmRYIbo0tKWbmo-pRi1iKjxfNvk7ttNuI0agA
rocketchat.userid=4v3hddMoiGjXRMzGm

