<?xml version="1.0" encoding="UTF-8"?>
<!-- This file is generated by Kaoto DataMapper. Do not edit. -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="3.0" xmlns:xf="http://www.w3.org/2005/xpath-functions">
    <xsl:output method="text" indent="yes"/>
    <xsl:param name="rocketchat"/>
    <xsl:variable name="rocketchat-x" select="json-to-xml($rocketchat)"/>
    <xsl:variable name="mapped-xml">
        <map xmlns="http://www.w3.org/2005/xpath-functions">
            <string key="timestamp">
                <xsl:value-of select="$rocketchat-x/xf:map/xf:string[@key='timestamp']"/>
            </string>
            <string key="source">
                <xsl:value-of select="&quot;rocketchat&quot;"/>
            </string>
            <string key="user">
                <xsl:value-of select="$rocketchat-x/xf:map/xf:string[@key='user_name']"/>
            </string>
            <string key="text">
                <xsl:value-of select="$rocketchat-x/xf:map/xf:string[@key='text']"/>
            </string>
        </map>
    </xsl:variable>
    <xsl:template match="/">
        <xsl:value-of select="xml-to-json($mapped-xml)"/>
    </xsl:template>
</xsl:stylesheet>